# Generated by Django 4.1.2 on 2022-10-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnTheGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('cartype', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=60)),
                ('booked_on', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('cartype', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('booked_on', models.CharField(max_length=30)),
            ],
        ),
    ]
