# Generated by Django 4.1.2 on 2022-10-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onthego',
            old_name='booked_on',
            new_name='Booked_on',
        ),
        migrations.RenameField(
            model_name='scheduleride',
            old_name='booked_on',
            new_name='Booked_on',
        ),
    ]
