# Generated by Django 4.1.2 on 2022-11-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0003_remove_onthego_booked_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedForLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('cartype', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='RidesRightNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('cartype', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='OnTheGo',
        ),
        migrations.DeleteModel(
            name='ScheduleRide',
        ),
    ]
